# -*- coding: utf-8 -*-
"""Leetcode 168 Excel Sheet Column Title.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n09ivRBB03NQMYuwunr1HKxLyos_tvRb
"""

#def convertToTitle(self, columnNumber: int) -> str:
def convertToTitle(columnNumber):
  s = ""
  Q = columnNumber
  while Q > 0:
    Q,R = divmod(Q-1,26)
    s += chr(65+R)
    
  return s[::-1]

convertToTitle(25)

convertToTitle(676)

convertToTitle(702)

convertToTitle(1000)