# -*- coding: utf-8 -*-
"""Leetcode 451 Sort Characters By Frequency.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15J1PaRjWQmRzzOL4NlqH7dwW4gpcPvp7
"""

class Solution:
    def frequencySort(self, s: str) -> str:
        mapping = {}
        for char in s:
            if char in mapping:
                mapping[char] += 1
            else:
                mapping[char] = 1
        mapping = {k:v for k,v in sorted(mapping.items(), key=lambda mapping: mapping[1], reverse=True)}
        result = ''
        for k,v in mapping.items():
            result += k*v
        return result