# -*- coding: utf-8 -*-
"""Leetcode 716 Max Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fx7CMvhu6O1lNTjJIuLvuWzCEkADAj-k
"""

class MaxStack:

    def __init__(self):
        """
        initialize your data structure here.
        """
        self.stack = []

    def push(self, x: int) -> None:
        if self.stack:
            self.stack.append((x,max(self.stack[-1][1],x)))
        else:
            self.stack.append((x,x))

    def pop(self) -> int:
        if self.stack:
            return self.stack.pop()[0]

    def top(self) -> int:
        if self.stack:
            return self.stack[-1][0]

    def peekMax(self) -> int:
        if self.stack:
            return self.stack[-1][1]

    def popMax(self) -> int:
        m = self.stack[-1][1]
        temp = []
        while self.stack[-1][0] != m:
            temp.append(self.stack.pop())

        self.stack.pop()
        for t in reversed(temp):
            self.push(t[0])
        return m


# Your MaxStack object will be instantiated and called as such:
# obj = MaxStack()
# obj.push(x)
# param_2 = obj.pop()
# param_3 = obj.top()
# param_4 = obj.peekMax()
# param_5 = obj.popMax()