# -*- coding: utf-8 -*-
"""Leetcode 841 Keys and Rooms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVkViyaIhqE6TRXhdd8op8HFpnxOi6CN
"""

class Solution:
    def canVisitAllRooms(self, rooms):
        visited = set()
        stack = []
        
        stack.append(0)
        while stack:
            curr = stack.pop()
            if curr not in visited:
                visited.add(curr)
                for key in rooms[curr]:
                    if key not in visited:
                        stack.append(key)
        return len(visited) == len(rooms)

s = Solution()

print(f'Output: {s.canVisitAllRooms(rooms = [[1],[2],[3],[]])}')

print(f'Output: {s.canVisitAllRooms(rooms = [[1,3],[3,0,1],[2],[0]])}')

