# -*- coding: utf-8 -*-
"""Leetcode 997 Find the Town Judge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWFORSXVy9VnSn3W5kUS22uT0m_ns_DE
"""

class Solution:
    def findJudge(self, n, trust):
        if len(trust) < n-1:
            return -1
        if len(trust) == 0 and n==1:
            return 1
        
        trust_scores = [0]*(n+1)
        for t in trust:
            trust_scores[t[0]] -= 1
            trust_scores[t[1]] += 1
            
        for indx,score in enumerate(trust_scores):
            if score == (n-1):
                return indx
        return -1

s = Solution()

print(f'Output: {s.findJudge(n = 2, trust = [[1,2]])}')

print(f'Output: {s.findJudge(n = 3, trust = [[1,3],[2,3]])}')

