# -*- coding: utf-8 -*-
"""Leetcode 359 Logger Rate Limiter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PXbzGJ1G91XBDfNpTTu2W4kifjOiA4H
"""

class Logger:

    def __init__(self):
        self.logs = {}

    def shouldPrintMessage(self, timestamp: int, message: str) -> bool:
        if message not in self.logs:
            self.logs[message] = timestamp + 10
        else:
            if timestamp >= self.logs[message]:
                self.logs[message] = timestamp + 10
            else:
                return False
        return True
                


# Your Logger object will be instantiated and called as such:
# obj = Logger()
# param_1 = obj.shouldPrintMessage(timestamp,message)