# -*- coding: utf-8 -*-
"""Leetcode 1528 Shuffle String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RrbRtuuGN6wKU4Tr5FzfH93zIqvmTVD
"""

class Solution:
    def restoreString(self, s, indices):
        result=[0]*len(s)
        for indx,charc in zip(indices,s):
            result[indx]=charc
        return ''.join(result)

#Input: s = "codeleet", indices = [4,5,6,7,0,2,1,3]
#Output: "leetcode"
#Explanation: As shown, "codeleet" becomes "leetcode" after shuffling.

sln = Solution()
s = "codeleet"
indices = [4,5,6,7,0,2,1,3]
print(f'Output:{sln.restoreString(s, indices)}')

