# -*- coding: utf-8 -*-
"""Leetcode 237 Delete Node in a Linked List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vSbPhX-9RYQOw54rfDuLtB2TekjEWSnQ
"""

# Definition for singly-linked list.
class ListNode:
  def __init__(self, x):
    self.val = x
    self.next = None

class Solution:
  def deleteNode(self, node):
    """
    :type node: ListNode
    :rtype: void Do not return anything, modify node in-place instead.
    """
    node_to_del = node.next
    node.val = node.next.val
    node.next = node.next.next
    del node_to_del

l4 = ListNode(9)
l3 = ListNode(1)
l3.next = l4
l2 = ListNode(5)
l2.next = l3
head = ListNode(4)
head.next = l2

s = Solution()

s.deleteNode(l2)

ll = head
while ll:
  print(ll.val)
  ll = ll.next

