# -*- coding: utf-8 -*-
"""Leetcode 1791 Find Center of Star Graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XovRshv4bhg-lbVszY4WHpwL3opHQZRg
"""

class Solution:
    def findCenter(self, edges):
        return edges[0][0] if edges[0][0] in edges[1] else edges[0][1]

s = Solution()

print(f'Output: {s.findCenter(edges = [[1,2],[2,3],[4,2]])}')

print(f'Output: {s.findCenter(edges = [[1,2],[5,1],[1,3],[1,4]])}')

