# -*- coding: utf-8 -*-
"""Leetcode 1281 Subtract the Product and Sum of Digits of an Integer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lWY71cC1f6oWkvxTHKW3zosmuIKmOd1F
"""

class Solution:
    def subtractProductAndSum(self, n):
        nsum = 0
        nprod = 1
        while n > 0:
            nsum += n%10
            nprod *= n%10
            n = n//10
        return nprod-nsum

#Input: n = 234
#Output: 15 
#Explanation: 
#Product of digits = 2 * 3 * 4 = 24 
#Sum of digits = 2 + 3 + 4 = 9 
#Result = 24 - 9 = 15

s = Solution()
n = 234
print(f'Output:{s.subtractProductAndSum(n)}')

