# -*- coding: utf-8 -*-
"""Leetcode 1047 Remove All Adjacent Duplicates In String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15U773_cPyPCr2r1RbpcoIsqGszFQAriW
"""

class Solution:
    def removeDuplicates(self, s):
        stack = []
        for st in s:
            if not stack or st!=stack[-1]:
                stack.append(st)
            else:
                stack.pop()
        return "".join(stack)

s = Solution()

print(f'Output: {s.removeDuplicates(s = "abbaca")}')

