# -*- coding: utf-8 -*-
"""Leetcode 345 Reverse Vowels of a String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7RM8K-eIG-mvg8ZTW7f055KFE_XWzrA
"""

def reverseVowels(s):
  vowels = ['a','e','i','o','u','A','E','I','O','U']
  s_list = list(s)
  i = 0
  j = len(s)-1
  while i < j:
    while i<j and s_list[i] not in vowels:
      i += 1
    while i<j and s_list[j] not in vowels:
      j -= 1
    s_list[i],s_list[j] = s_list[j],s_list[i]
    i += 1
    j -= 1
  return ''.join(s_list)

#Input: s = "leetcode"
#Output: "leotcede"

print(f'Output: {reverseVowels("leetcode")}')

print(f'Output: {reverseVowels("race car")}')

print(f'Output: {reverseVowels("aA")}')

