# -*- coding: utf-8 -*-
"""Leetcode 541 Reverse String II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TYSWFw3KnW4f4Ph4cwHXcr-fTNUpxQDC
"""

class Solution:
    def reverseStr(self, s, k):
        '''
        s_list = list(s)
        for n in range(0,len(s),2*k):
            i = n
            j=(n-1)+k
            if len(s)-i > k:
                if j-i<=2*k:
                    while i<j:
                        s_list[i],s_list[j] = s_list[j],s_list[i]
                        i += 1
                        j -= 1
            else:
                j = len(s)-1
                while i<j:
                    s_list[i],s_list[j] = s_list[j],s_list[i]
                    i += 1
                    j -= 1

            
        return ''.join(s_list)
        '''

        reverse=True
        result=""
        for i in range(0,len(s),k):
            block = s[i:i+k]
            print(block)
            if reverse:
                result+=block[::-1]
            else:
                result+=block
            reverse = not reverse
        return result

s = Solution()

print(f'Output: {s.reverseStr("abcdefg",8)}')

