# -*- coding: utf-8 -*-
"""Leetcode 404 Sum of Left Leaves.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBtx8cVY5IfnADhHflrnEEzkuZe-6L2u
"""

# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def sumOfLeftLeaves(self, root: Optional[TreeNode]) -> int:
        return self.dfs(root,0)
    
    def dfs(self, root, side):
        if not root:
            return 0
        if not root.left and not root.right:
            if side == 1:
                return root.val
        
        return self.dfs(root.left,1) + self.dfs(root.right,-1)