# -*- coding: utf-8 -*-
"""Leetcode 1342 Number of Steps to Reduce a Number to Zero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WBtXmPlJGkvS21Vz0p91fdBdUnwXkUm7
"""

def numberOfSteps(num):
  count = 0
  while num>0:
    count += 1
    if num%2 == 0:
      num /= 2
    else:
      num -= 1
  return count

#Input: num = 14
#Output: 6
#Explanation: 
#Step 1) 14 is even; divide by 2 and obtain 7. 
#Step 2) 7 is odd; subtract 1 and obtain 6.
#Step 3) 6 is even; divide by 2 and obtain 3. 
#Step 4) 3 is odd; subtract 1 and obtain 2. 
#Step 5) 2 is even; divide by 2 and obtain 1. 
#Step 6) 1 is odd; subtract 1 and obtain 0.

print(f'Output:{numberOfSteps(14)}')

