# -*- coding: utf-8 -*-
"""Leetcode 1672 Richest Customer Wealth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-wp5vX5nVCS8hx4B35Tc89V4Uar-dct
"""

def maximumWealth(accounts):
  max_amount = -100
  for a in accounts:
    max_amount = max(max_amount,sum(a))
  return max_amount

#Input: accounts = [[1,2,3],[3,2,1]]
#Output: 6

acc = [[1,2,3],[3,2,1]]

print(f'Richest = {maximumWealth(acc)}')

