# -*- coding: utf-8 -*-
"""Leetcode 383 Ransom Note.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsD--xAV1E2QADIBCfjFHvZIL2rdgWav
"""

from collections import Counter
class Solution:
    def canConstruct(self, ransomNote: str, magazine: str) -> bool:
        if len(ransomNote) > len(magazine): return False 
        magazine_counts = Counter(magazine)
        for ch in ransomNote:
            if ch not in magazine_counts:
                return False
            if magazine_counts[ch] <= 0:
                return False
            magazine_counts[ch] -= 1

        return True
        
    def canConstruct2(self, ransomNote: str, magazine: str) -> bool:
        if len(ransomNote) > len(magazine): return False 
        magazine_counts = Counter(magazine)
        for ch in ransomNote:
            if magazine_counts[ch] <= 0:
                return False
            magazine_counts[ch] -= 1

        return True

s = Solution()

print(f'Output: {s.canConstruct(ransomNote = "aa", magazine = "aab")}')

print(f'Output: {s.canConstruct(ransomNote = "aab", magazine = "baa")}')

print(f'Output: {s.canConstruct(ransomNote = "xyz", magazine = "baa")}')

