# -*- coding: utf-8 -*-
"""Leetcode 69 Sqrt(x).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7xAlj3Y5lCOkPoGzyhTKDRrniiYKZxA
"""

def mySqrt(x):
  '''
  y=ans
  x = y^2
  to find y binary search can be used
  '''
        
  if x < 2:
    return x
    
  left, right = 2, x // 2
  
  while left <= right:
    pivot = left + (right - left) // 2
    num = pivot * pivot
    if num > x:
      right = pivot -1
    elif num < x:
      left = pivot + 1
    else:
      return pivot
  return right

#Input: x = 8
#Output: 2
#Explanation: The square root of 8 is 2.82842..., and since the decimal part is truncated, 2 is returned.

x = 8
print(f'Output: {mySqrt(x)}')

