# -*- coding: utf-8 -*-
"""Leetcode 1603 Design Parking System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7kXiVVYVWVUOGk5BZ5D_hK9Gm_xkh_D
"""

class ParkingSystem:
    def __init__(self, big: int, medium: int, small: int):
      self.big = big
      self.medium = medium
      self.small = small

    def addCar(self, carType):
      #Initialize the return value as False (slot not available)
      result = False
      
      #If it is big car
      if carType == 1:
        #Check if any slots are available, if yes
        if self.big > 0:
          #Reduce the available slot by 1
          self.big -= 1
          #Set the return value as True (slot available)
          result = True
      #If it is medium car
      elif carType == 2:
        if self.medium > 0:
          self.medium -= 1
          result = True
      #If it is small car
      elif carType == 3:
        if self.small > 0:
          self.small -= 1
          result = True
      
      #Finally return the availability
      return result

p = ParkingSystem(1, 1, 0)

p.addCar(1)

p.addCar(2)

p.addCar(3)

p.addCar(1)

