# -*- coding: utf-8 -*-
"""Leetcode 1389 Create Target Array in the Given Order.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4CIiCkO8Neh_jd-nQFSLOegIKWu0kky
"""

def createTargetArray(nums,index):
  result = []
  for i,v in zip(index,nums):
    result.insert(i,v)
  return result

#Input: nums = [0,1,2,3,4], index = [0,1,2,2,1]
#Output: [0,4,1,3,2]
#Explanation:
#nums       index     target
#0            0        [0]
#1            1        [0,1]
#2            2        [0,1,2]
#3            2        [0,1,3,2]
#4            1        [0,4,1,3,2]

input_nums = [0,1,2,3,4]
input_index = [0,1,2,2,1]

print(f'Output:{createTargetArray(input_nums,input_index)}')

