# -*- coding: utf-8 -*-
"""Leetcode 1313 Decompress Run-Length Encoded List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZsEQGgMEicsyno5T-JlJ6RQPT6xZDgg
"""

def decompressRLElist(nums):
  result = []
  for i in range(0,len(nums),2):
    result.extend(nums[i]*[nums[i+1]])
  return result

#Input: nums = [1,2,3,4]
#Output: [2,4,4,4]
#Explanation: The first pair [1,2] means we have freq = 1 and val = 2 so we generate the array [2].
#The second pair [3,4] means we have freq = 3 and val = 4 so we generate [4,4,4].
#At the end the concatenation [2] + [4,4,4] is [2,4,4,4].

nums = [1,2,3,4]
print(f'Output:{decompressRLElist(nums)}')

