# -*- coding: utf-8 -*-
"""Leetcode 692 Top K Frequent Words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EdbZ3ya__TKgsqKP04-0OVKY8l_SAdH
"""

import collections
import heapq
class Solution:
    def topKFrequent(self, words, k):
        word_count = self.get_word_count(words)
        word_count_pairs = []
        for word,count in word_count.items():
            word_count_pairs.append((-count,word))
        heapq.heapify(word_count_pairs)
        return [heapq.heappop(word_count_pairs)[1] for _ in range(k)]
    
    def get_word_count(self, words):
        result = collections.defaultdict(int)
        for w in words:
            result[w] += 1
        return result

s = Solution()

print(f'Output: {s.topKFrequent(words = ["i","love","leetcode","i","love","coding"], k = 2)}')

print(f'Output: {s.topKFrequent(words = ["the","day","is","sunny","the","the","the","sunny","is","is"], k = 4)}')

