# -*- coding: utf-8 -*-
"""Leetcode 84 Largest Rectangle in Histogram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJfBOuIAVFR_SvdCoyDTssXZ_yaIO9RC
"""

class Solution:
    def largestRectangleArea(self, heights):
        stack = []
        stack.append(-1)
        n = len(heights)
        max_area = 0
        for i in range(n):
            while stack[-1]!=-1 and heights[stack[-1]] >= heights[i]:
                current_height = heights[stack.pop()]
                current_width = i - stack[-1] - 1 
                max_area = max(max_area, current_height*current_width)
            stack.append(i)
        
        while stack[-1] != -1:
            current_height = heights[stack.pop()]
            current_width = n - stack[-1] - 1
            max_area = max(max_area, current_height*current_width)
        
        return max_area

s = Solution()

print(f'Output: { s.largestRectangleArea(heights = [2,1,5,6,2,3])}')

