# -*- coding: utf-8 -*-
"""Leetcode 766 Toeplitz Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j0OSPMKcoib4VUn3xx69xoU3daEfNNGn
"""

class Solution:
    def isToeplitzMatrix(self, matrix):
        groups = {}
        for r, row in enumerate(matrix):
            for c, val in enumerate(row):
                if r-c not in groups:
                    groups[r-c] = val
                elif groups[r-c] != val:
                    return False
        return True

s = Solution()

print(f'Output: {s.isToeplitzMatrix(matrix = [[1,2,3,4],[5,1,2,3],[9,5,1,2]])}')

