# -*- coding: utf-8 -*-
"""Leetcode 186 Reverse Words in a String II.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWhbqB-n77LThAxFFsyNDBSNY69WObGs
"""

class Solution:
    def reverse(self, lst, start, end):
        while start < end:
            lst[start], lst[end] = lst[end], lst[start]
            start += 1
            end -= 1
            
    def reverse_word(self, lst):
        i = j = 0
        while i < len(lst):
            while j < len(lst) and lst[j] != ' ':
                j += 1
            self.reverse(lst, i, j-1)
            i = j + 1
            j = j + 1
            
    def reverseWords(self, s):
        """
        Do not return anything, modify s in-place instead.
        """
        self.reverse(s,0,len(s)-1)
        self.reverse_word(s)

class_s_obj = Solution()

list_s = ["t","h","e"," ","s","k","y"," ","i","s"," ","b","l","u","e"]
list_s

class_s_obj.reverseWords(list_s)

list_s

