# -*- coding: utf-8 -*-
"""Leetcode 557 Reverse Words in a String III.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cgO7Al3bugXtdwhp4Ik88VXBTLAj4D2R
"""

class Solution:
    def reverseWords(self, s):
        list_s=s.split(' ')
        for i in range(len(list_s)):
            list_s[i] = list_s[i][::-1]
        return ' '.join(list_s)

s=Solution()

str_s = "Let's take LeetCode contest"
print(f'Output: {s.reverseWords(str_s)}')

