# -*- coding: utf-8 -*-
"""Leetcode 1929 Concatenation of Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxvVolYoZ-r7qfb8jYVrgSY5Vh7MZ_LW
"""

class Solution:
    def getConcatenation(nums):
      ans = []
      ans = nums
      ans[len(nums):] = nums
      return ans

nums1 = [1,2,3]

print(f'Output is {Solution.getConcatenation(nums=nums1)}')

